# Пароль для подключения
# requirepass your_secure_password
user admin_user on >your_secure_password ~* &* +@all
user default off
# Включение сохранения (AOF)
appendonly yes

# Разрешить подключения со всех IP (внутри сети Docker)
bind 0.0.0.0
